language: generic
env:
  global:
    - IDE_VERSION=1.6.10E18
  matrix:
    - BOARD="energia:tivac:EK-TM4C123GXL"
    - BOARD="energia:cc3200:CC3200-LAUNCHXL"

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://energia.nu/downloads/downloadv4.php?file=energia-$IDE_VERSION-linux64.tar.xz -O energia-$IDE_VERSION-linux64.tar.xz
  - tar xf energia-$IDE_VERSION-linux64.tar.xz
  - mv energia-$IDE_VERSION $HOME/energia-ide
  - export PATH=$PATH:$HOME/energia-ide

  - if [[ "$BOARD" =~ "energia:tivac:" ]]; then
      energia --install-boards energia:tivac:
    fi

  - if [[ "$BOARD" =~ "energia:cc3200:" ]]; then
      energia --install-boards energia:cc3200:
      energia --install-library WiFi;
    fi

  - findAndReplace() { sed -i'' -e"s|$1|$2|g" "$3"; }
  - buildExampleSketch() {
      EXAMPLE_SKETCH=$PWD/examples/$1/$1.ino;

      cat $EXAMPLE_SKETCH;
      energia --verbose-build --verify --board $BOARD $EXAMPLE_SKETCH;
    }

install:
  - ln -s $PWD $HOME/Energia/libraries/.

script:
  - buildExampleSketch Date_String
  - buildExampleSketch CC3200_NTP